# The Architect MVP network
# testnet/network 
#
# Use `ethereum/client-go:alpine` for slim node (network on local/Raspberry Pi)
FROM ethereum/client-go:alpine

LABEL maintainer="rohanmishra2017@gmail.com"

