# testnet/network 
# Dockerfile
#
# Use `ethereum/client-go:alpine` for slim node (network on local/Raspberry Pi)
FROM ethereum/client-go:alpine

LABEL version="1.0"
LABEL maintainer="rohanmishra2017@gmail.com"

# s/o @fishbullet
# RUN adduser -D -g "" arch_usr

